<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Refit.HttpClientFactory" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" />
    <ProjectReference Include="..\..\Shared\Platform.Shared.Contracts\Platform.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\Platform.Shared.Infrastructure\Platform.Shared.Infrastructure.csproj" />
  </ItemGroup>
</Project>
