// <auto-generated />
using System;
using GraphService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GraphService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GraphDbContext))]
    [Migration("20260911011239_AddGraphClusterSummaryBodies")]
    partial class AddGraphClusterSummaryBodies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GraphService.Domain.AiSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EdgeTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset?>("ReinstatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReinstatedReason")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RejectedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TagValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TargetDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_ai_suggestions_state");

                    b.HasIndex("SourceDocumentId", "TargetDocumentId")
                        .HasDatabaseName("ix_ai_suggestions_endpoints");

                    b.ToTable("ai_suggestions", (string)null);
                });

            modelBuilder.Entity("GraphService.Domain.Clustering.GraphCluster", b =>
                {
                    b.Property<Guid>("ClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompositionChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.HasKey("ClusterId");

                    b.ToTable("graph_clusters", (string)null);
                });

            modelBuilder.Entity("GraphService.Domain.Clustering.GraphClusterMember", b =>
                {
                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("ClusterId", "DocumentId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_graph_cluster_members_document");

                    b.ToTable("graph_cluster_members", (string)null);
                });

            modelBuilder.Entity("GraphService.Domain.Clustering.GraphClusterSummary", b =>
                {
                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Confidentiality")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClusterId", "Confidentiality");

                    b.ToTable("graph_cluster_summaries", (string)null);
                });

            modelBuilder.Entity("GraphService.Domain.Clustering.GraphClusterSummaryBody", b =>
                {
                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Confidentiality")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClusterId", "Confidentiality");

                    b.ToTable("graph_cluster_summary_bodies", (string)null);
                });

            modelBuilder.Entity("GraphService.Domain.DocumentLinkTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("SourceDocumentId")
                        .HasDatabaseName("ix_document_link_targets_source");

                    b.ToTable("document_link_targets", (string)null);
                });

            modelBuilder.Entity("GraphService.Domain.Edge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EdgeTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExtractedFrom")
                        .HasColumnType("uuid");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceAnchor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetAnchor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<Guid>("TargetDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EdgeTypeId")
                        .HasDatabaseName("ix_edges_type");

                    b.HasIndex("ExtractedFrom")
                        .HasDatabaseName("ix_edges_extracted_from");

                    b.HasIndex("SourceDocumentId")
                        .HasDatabaseName("ix_edges_source");

                    b.HasIndex("TargetDocumentId")
                        .HasDatabaseName("ix_edges_target");

                    b.HasIndex("SourceDocumentId", "TargetDocumentId", "EdgeTypeId", "SourceAnchor", "TargetAnchor")
                        .IsUnique()
                        .HasDatabaseName("ux_edges");

                    b.ToTable("edges", (string)null);
                });

            modelBuilder.Entity("GraphService.Domain.EdgeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSymmetric")
                        .HasColumnType("boolean");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.5);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_edge_types_name");

                    b.ToTable("edge_types", (string)null);
                });

            modelBuilder.Entity("GraphService.Domain.GraphDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BodyHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("BodyUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocumentId");

                    b.ToTable("graph_documents", (string)null);
                });

            modelBuilder.Entity("GraphService.Domain.GraphDocumentTermProfile", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocumentId");

                    b.ToTable("graph_document_term_profiles", (string)null);
                });

            modelBuilder.Entity("GraphService.Domain.Clustering.GraphClusterMember", b =>
                {
                    b.HasOne("GraphService.Domain.Clustering.GraphCluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GraphService.Domain.Clustering.GraphClusterSummary", b =>
                {
                    b.HasOne("GraphService.Domain.Clustering.GraphCluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GraphService.Domain.Clustering.GraphClusterSummaryBody", b =>
                {
                    b.HasOne("GraphService.Domain.Clustering.GraphCluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GraphService.Domain.Edge", b =>
                {
                    b.HasOne("GraphService.Domain.EdgeType", null)
                        .WithMany()
                        .HasForeignKey("EdgeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
